(TeX-add-style-hook "bibliography"
 (function
  (lambda ()
    (LaTeX-add-bibitems
     "ebay2005q1"
     "kdd2002web"
     "CACMReputationSystems"
     "KauffmanWood"
     "DellarocasACMEC2000"
     "kagel02:"
     "sinhagreenleaf-covertshilling2000"
     "snyder-fraudstop2000"
     "hidvegiwangwhinston-englishshill"
     "hidvegiwangwhinston-spf"
     "resnickzeckhauser-ebayreputation2002"
     "brinkmannseifert-auctiontrust2001"
     "dellarocas-wordofmouth2003"
     "dellarocas-onlinereputation"
     "houserwooders-ebayreputation2004"
     "livingston-howvaluable2005"
     "melnikalm-reputationmatters2002"
     "resnickzeckhauserswansonlockwood-reputationexperiment2004"
     "standifird01-asymmetricalreputation2001"
     "yamagishi-roleofreputation"
     "ebay-policy"
     "uslaw-mailfraud"
     "nilsonreport-march2005"
     "dudahardstork-patternclassif2000"
     "brauselangsdorfhepp-ccfraud1999"
     "moreauverrelstvandewalle-mobilefraud1997"
     "boltonhand-fraudreview2002"
     "neculamcpeakweimer-ccured2002"
     "leestolfomok-idsdatamining1999"
     "lee-thesis1999"
     "krugeltothkirda-servicespecificnids2002"))))

